# Generated by Django 5.0.2 on 2024-02-19 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AAA', '0002_user_created_at_user_last_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended')], default='inactive', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Admin'), ('moderator', 'Moderator'), ('subscriber', 'Subscriber'), ('free_user', 'Free User')], default='free_user', max_length=50),
        ),
    ]
