# Generated by Django 5.0.2 on 2024-02-20 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AAA', '0003_user_status_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('subscriber', 'Subscriber'), ('free_user', 'Free User')], default='free_user', max_length=50),
        ),
    ]
